apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-argocd-app
  namespace: argocd-deployment
spec:
  project: default

  source:
    repoURL: https://gitlab.com/gunturginting/argocd.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
